config/routes.rb
Rails.application.routes.draw do
    
  root to: 'homes#top'
  resources :books
  
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def create
    @list = Book.new(book_params)
     if @list.save
       flash[:notice] = "Book was successfully created."
       redirect_to book_path (@list.id)
     else
       @books=Book.all
       render :index

     end
  end

  def index
    @list=Book.new
    @books = Book.all
  end


  def show
    @list= Book.find(params[:id])
     @list.save
      

  end



  def edit
    @list= Book.find(params[:id])
    @list.save
  end




  def update
        @list = Book.find(params[:id])
        @list.update(book_params)
    if  @list. save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@list.id)
    else
        render :edit
    end
  end



  def destroy
    list = Book.find(params[:id])
    list.destroy
    redirect_to books_path
  end



  private
  # ストロングパラメータ
   def book_params
    params.require(:book).permit(:title, :body)
   end
   end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div class=editbook>
  <h2>Editing Book</h2>
<%= form_with model: @list, url: book_path(@list.id), method: :patch do |f| %>

<% if @list.errors.any? %>
  <%= @list.errors.count %>errors prohibited this book from being saved:

  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>






    <div class ="T">Title</div>
    <%= f.text_field :title %>

    <div class ="B">Body</div>
    <%= f.text_area :body %>

    <br><%= f.submit 'Update Book'%>
 <% end %>

 <%= link_to 'Show',book_path %> | <%= link_to 'Back',books_path %>
</div>

app/views/books/index.html.erb
<div class="group">
<h2>Books</h2>

 <table>

     <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
        </tr>
     </thead>



     <tbody>
      <% @books.each do |book| %>
        <tr>
             <td><%= book.title %></td>
             <td><%= book.body %></td>
            
              <td><%= link_to "Show",book_path(book.id)%></td>
              
              <td><%= link_to "Edit",edit_book_path(book.id) %></td>
            　
            　<td><%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
             
        </tr>
       <% end %>
     </tbody>
  </table>




<div class=newbook>
  <h2>New book</h2>

       <% if @list.errors.any? %>
<%= @list.errors.count %>errors prohibited this book from being saved:

    <ul>
         <% @list.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
    </ul>
<% end %>




  <%= form_with model: Book.new do |f| %>
    <p>Title</p>
    <%= f.text_field :title %>

    <p>Body</p>
    <%= f.text_area :body %>

    <br><%= f.submit 'Create Book' %>
 <% end %>

 </div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="show">

   <div class="flash">
     <%= flash[:notice] %>
   </div>

   <div class="showbox">
   　<div class="showtitle">Title:<%= @list.title %></div>
     <div class="showbody">Body:<%= @list.body %></div>  
   </div> 
   


<div class="next">
 <%= link_to 'Edit',edit_book_path %> | <%= link_to 'Back',books_path %>
</div>

 </div>

app/views/homes/top.html.erb
<div class="toppage">
    <h1>ようこそ Bookers へ！</h1>

     <div class="text">
         Bookersでは、さまざまな書籍に関するあなたの意見や
      <br>
        印象を共有し交換することができます
      <br>
         <%= link_to 'start',books_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>